### ISSUE TITLE
One more question about training the flow_HMDB51_64f model

### ISSUE THREAD

**Issue by qiuqicao77** [craston/MARS#10]
May i ask one more question? When the training the 64f Flow HMDB51 with the pretrained model 'Kinetics', however the accuracy of the 400 epoch model cannot reach the result as yours. Did you choose the last epoch model or others. Can you give me some advice on this?

**Comment by craston** [comment]
Could you please let me know what is difference in accuracy?

**Comment by qiuqicao77** [comment]
Hello, I already figure out why the acc in 400 Epoch is lower than yours! I
did the model search i found that the best performance is not occur in the
400 epoch, however is happen at 50 epoch.

craston <notifications@github.com> 于2019年9月25日周三 下午5:01写道：
