### ISSUE TITLE
A small query about finetuning

### ISSUE THREAD

**Issue by DAVEISHAN** [craston/MARS#14]
Hello, 

I want to finetune the MARS and MERS on my own dataset using pre-trained weights of Kinetics-400 provided by you. For that I need to extract optical flow from my dataset, right?

Thank you, for sharing this wonderful repo online! Hope to hear from you soon! 

Regards,
Ishan

**Comment by craston** [comment]
Yes, for finetuning MARS and MERS you need to extract optical flow for your dataset.

**Comment by Muhtasham** [comment]
Dear @craston ,
Thanks for amazing work.  
I'm interested in recognizing the activity of one specific video(mp4). Can you please guide me on how to do it? How can i extract optical flow from my mp4 video? After that how should i proceed?  

Waiting for your reply,
