### ISSUE TITLE
Could you share all of the finetune hyperparameters on hmdb51?

### ISSUE THREAD

**Issue by seominseok0429** [craston/MARS#18]
Could you share all of the finetune hyperparameters on hmdb51? For example, momentum, epoch, running rate ...

Thank you very much for a good Research.

**Comment by craston** [comment]
finetuning initial learning_rate = 0.001 (divide by 10 based on lr_scheduler)
finetuning weight_decay = 1e-5 
This is already taken care of [here].(https://github.com/craston/MARS/blob/ae2749dc37ec19821da69654e9197a52f0b45839/train.py#L82)
The remaining hyper-parameters are given in opts.py
