### ISSUE TITLE
Different results of HMDB-51

### ISSUE THREAD

**Issue by KT27-A** [craston/MARS#2]
Thank you very much for your work @craston. We really appreciate it. 

I tested the model of 'RGB_HMDB_51_16f' in HMDB split 1. But I just got the accuracy of 55.7% which is 66.7% in your paper. The command is as follows:
python test_single_stream.py --batch_size 1 --n_classes 51 --model resnext --model_depth 101 \
--log 0 --dataset HMDB51 --modality RGB --sample_duration 16 --split 1 --only_RGB  \
--resume_path1 "../pretrained_model/RGB_HMDB51_16f.pth" \
--frame_dir "../hmdb-51-1f" \
--annotation_path "dataset/HMDB51_labels" \
--result_path "results/" \
--n_workers 4

Did I make a mistake somewhere? Thank you very much.

**Comment by craston** [comment]
Did you extract the frames using the script utils1/extract_frames.py?

**Comment by KT27-A** [comment]
No. I extract the frames in my way but also based on ffmpeg. It seems that the difference may come from the extraction.

**Comment by KT27-A** [comment]
After extracting the frames by your method, the accuracy went to 66.8%, thank you very much for your advice. @craston

**Comment by KT27-A** [comment]
Hi, @craston , I found the labels of UCF-101 are missing in the cloud. Would you please add them so that we can test easily? Thank you very much.

**Comment by LikeCorley** [comment]
hello,@Katou2 ,Do you tested the model of 'RGB_HMDB_51_16f'  will the appear 
Traceback (most recent call last):
  File "/home/kl/data/MARS-master/test_single_stream.py", line 49, in <module>
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/kl/.conda/envs/python=3.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.bn1.num_batches_tracked", "module.layer1.0.bn1.num_batches_tracked", "module.layer1.0.bn2.num_batches_tracked", "module.layer1.0.bn3.num_batches_tracked", "module.layer1.0.downsample.1.num_batches_tracked", "module.layer1.1.bn1.num_batches_tracked", "module.layer1.1.bn2.num_batches_tracked", "module.layer1.1.bn3.num_batches_tracked", "module.layer1.2.bn1.num_batches_tracked", "module.layer1.2.bn2.num_batches_tracked", "module.layer1.2.bn3.num_batches_tracked", "module.layer2.0.bn1.num_batches_tracked", "module.layer2.0.bn2.num_batches_tracked", "module.layer2.0.bn3.num_batches_tracked", "module.layer2.0.downsample.1.num_batches_tracked", "module.layer2.1.bn1.num_batches_tracked", "module.layer2.1.bn2.num_batches_tracked", "module.layer2.1.bn3.num_batches_tracked", "module.layer2.2.bn1.num_batches_tracked", "module.layer2.2.bn2.num_batches_tracked", "module.layer2.2.bn3.num_batches_tracked", "module.layer2.3.bn1.num_batches_tracked", "module.layer2.3.bn2.num_batches_tracked", "module.layer2.3.bn3.num_batches_tracked", "module.layer3.0.bn1.num_batches_tracked", "module.layer3.0.bn2.num_batches_tracked", "module.layer3.0.bn3.num_batches_tracked", "module.layer3.0.downsample.1.num_batches_tracked", "module.layer3.1.bn1.num_batches_tracked", "module.layer3.1.bn2.num_batches_tracked", "module.layer3.1.bn3.num_batches_tracked", "module.layer3.2.bn1.num_batches_tracked", "module.layer3.2.bn2.num_batches_tracked", "module.layer3.2.bn3.num_batches_tracked", "module.layer3.3.bn1.num_batches_tracked", "module.layer3.3.bn2.num_batches_tracked", "module.layer3.3.bn3.num_batches_tracked", "module.layer3.4.bn1.num_batches_tracked", "module.layer3.4.bn2.num_batches_tracked", "module.layer3.4.bn3.num_batches_tracked", "module.layer3.5.bn1.num_batches_tracked", "module.layer3.5.bn2.num_batches_tracked", "module.layer3.5.bn3.num_batches_tracked", "module.layer3.6.bn1.num_batches_tracked", "module.layer3.6.bn2.num_batches_tracked", "module.layer3.6.bn3.num_batches_tracked", "module.layer3.7.bn1.num_batches_tracked", "module.layer3.7.bn2.num_batches_tracked", "module.layer3.7.bn3.num_batches_tracked", "module.layer3.8.bn1.num_batches_tracked", "module.layer3.8.bn2.num_batches_tracked", "module.layer3.8.bn3.num_batches_tracked", ...

The command is as follows:
--batch_size 1 --n_classes 51 --model resnext --model_depth 101 
--log 0 --dataset HMDB51 --modality RGB --sample_duration 16 --split 1 --only_RGB 
--resume_path1 "/home/kl/data/mars_RGB/RGB_HMDB51_16f.pth" 
--frame_dir "/home/kl/data/mars_RGB/HMDB/dataset/HMDB51_frames" 
--annotation_path "/home/kl/data/mars_RGB/HMDB/dataset/HMDB51_labels" 
--result_path "results/"

Can you tell me what went wrong，Thank you very much!

**Comment by KT27-A** [comment]
@LikeCorley Hi, Corley, the problem happened is that your version of Pytorch is lower than 0.4.1 at most of time. If you want to run correctly, you should add the above missing keys in your module.

**Comment by craston** [comment]
@Katou2 : The labels for UCF101 are available on the cloud. If its still not accessible please let me know.

**Comment by KT27-A** [comment]
@craston Thank you very much. That is so kind of you. But I encountered another problem.

I finetuned the pre-trained model of Kinetics on HMDB51 dataset. I tried many times and different hyperparameters. I could not get a model with 66.7% accuracy. My trained accuracy was around 62.5%. The frames were extracted by your method.  My command is as follows:

python train.py --dataset HMDB51 --modality RGB --split 1 --only_RGB \
--n_classes 400 --n_finetune_classes 51 \
--batch_size 32 --log 1 --sample_duration 16 \
--model resnext --model_depth 101 --ft_begin_index 4 \
--frame_dir "../hmdb-51-1f-256" \
--annotation_path "dataset/HMDB51_labels" \
--pretrain_path "../pretrained_model/RGB_Kinetics_16f.pth" \
--result_path "results/" 

Hyperparameters are 
lr = 0.001 	 momentum = 0.9 	 dampening = 0.9 	 weight_decay = 1e-05, 	 nesterov = False
LR patience =  10

Did I make a mistake somewhere? Thank you very much. BTW, it did not mention the hyperparameters in for finetuning in your paper, I guess the above parameters may be the parameters for finetuning.

**Comment by craston** [comment]
The hyperparameters are correct. Could you please check if only the last resnext block and the fully connected layer are being trained. In other words, the learning rate for the earlier layers should be 0

**Comment by KT27-A** [comment]
@craston Thank you very much for your reply. I have checked that the trained parameters are resnext block 4 and fully connected layer. All the printed parameters are shown as follows:

python train.py --dataset HMDB51 --modality RGB --split 1 --only_RGB --n_classes 400 --n_finetune_classes 51 --batch_size 32 --log 1 --sample_duration 16 --model resnext --model_depth 101 --ft_begin_index 4 --frame_dir "../hmdb-51-1f-256" --annotation_path "dataset/HMDB51_labels" --pretrain_path "../pretrained_model/RGB_Kinetics_16f.pth" --result_path "results_hmdb_resnext101/" 

Namespace(MARS=False, MARS_alpha=50, MARS_pretrain_path='', MARS_resume_path='', annotation_path='dataset/HMDB51_labels', batch_size=32, begin_epoch=1, checkpoint=2, dampening=0.9, dataset='HMDB51', frame_dir='../hmdb-51-1f-256', freeze_BN=False, ft_begin_index=4, highest_val={'name': 0}, input_channels=3, learning_rate=0.1, log=1, lr_patience=10, manual_seed=1, modality='RGB', model='resnext', model_depth=101, momentum=0.9, n_classes=400, n_epochs=400, n_finetune_classes=51, n_workers=4, nesterov=False, only_RGB=True, optimizer='sgd', output_layers=[], pretrain_path='../pretrained_model/RGB_Kinetics_16f.pth', random_seed=1, resnet_shortcut='B', resnext_cardinality=32, result_path='results_hmdb_resnext101/', resume_path1='', resume_path2='', resume_path3='', sample_duration=16, sample_size=112, split='1', training=True, weight_decay=0.001)

Preprocessing train data ...
Length of train data =  3563
Preprocessing validation data ...
Length of validation data =  1523
Preparing datatloaders ...
Length of train datatloader =  111
Length of validation datatloader =  47
Loading model...  resnext 101
loading pretrained model ../pretrained_model/RGB_Kinetics_16f.pth
Layers to finetune :  ['layer4', 'fc']
Initializing the optimizer ...
lr = 0.001 	 momentum = 0.9 	 dampening = 0.9 	 weight_decay = 1e-05, 	 nesterov = False
LR patience =  10

Is there any problem? Thank you very much.

**Comment by craston** [comment]
Hi @Katou2, sorry for the late reply. There was bug in the dataset.py file which has been corrected.

**Comment by KT27-A** [comment]
Hi @craston , thank you very much for your modification. Now the accuracy is consistent with that in paper. Thanks a lot.
