### ISSUE TITLE
Flow Network For Fine-Tuning

### ISSUE THREAD

**Issue by artest08** [craston/MARS#20]
Thank you for your good effort. 

I want to ask that for fine-tuning models(MARS or MERS) in smaller datasets such as HMDB-51, as a teacher network, did you utilize Flow network trained on Kinetics-400, or Flow network fine-tuned on HMDB-51 dataset?

**Comment by craston** [comment]
For finetuning MARS/MERS on HDMB51, I used the flow-network fine-tuned on HDMB51 dataset
