### ISSUE TITLE
Run pre-trained model on single video

### ISSUE THREAD

**Issue by pittyacg** [craston/MARS#22]
Hi, I would like to use the pre-trained weights on HMDB to infer the model on a single random video and get the actions from that video? Can you give me a little help with the steps required? What pre-processing does the video require?

Petru

**Comment by craston** [comment]
Hi,
Basic steps:
1. Read your video using cv2.VideoCapture [(example)](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html)
2. Create a video clip of 16 or 64 frames depending on the model and preprocess it.
3. Feed this preprocessed clip to the model.
4. You could try overlapping clips to get a better prediction.
