### ISSUE TITLE
HMDB51 testing error!!!!

### ISSUE THREAD

**Issue by KP1-cmd** [craston/MARS#29]
i have extracted frames from videos and RGB_HMDB51_16f.pth as you mention in Readme but whenever i try to test the script i get the following error.can you you please help me out to solve this issue. Thank you.

![Screenshot from 2020-09-30 12-40-37](https://user-images.githubusercontent.com/58297850/94644109-0488b300-031b-11eb-986d-51e7801f7b68.png)

**Comment by superctj** [comment]
Have you solved this issue? I have the same issue when testing the single-stream MARS on UCF101.

**Comment by craston** [comment]
Since the length of the validation data = 0, it seems that it cannot find the frames. 
Could you please check the output of this [line](https://github.com/craston/MARS/blob/ae2749dc37ec19821da69654e9197a52f0b45839/dataset/dataset.py#L33)

**Comment by superctj** [comment]
Thank you for your response! I figured it out that I had to change code a little bit to accommodate my own data directory structure
