### ISSUE TITLE
random frame is not working?

### ISSUE THREAD

**Issue by nulli9** [craston/MARS#3]
Hi,

https://github.com/craston/MARS/blob/b70644381c45e03b8c0b7d62591754d677062f3a/dataset/dataset.py#L96
'start_frame' is not used, meaning always fetching the same clip from the first frame for each video.

Am I missing anything?

Thank you very much

**Comment by craston** [comment]
Hi, Thanks for spotting the bug. I've made the necessary changes to dataset.py

**Comment by wutongshu819274135** [comment]
if you use  np.random.randint，The pictures entered in this way are not in order
