### ISSUE TITLE
how to train two-stream(RGB+Flow) Network?

### ISSUE THREAD

**Issue by XDLiuyyy** [craston/MARS#41]
Thank you for publishing this good work!
In your paper, you have mentioned the result of two-stream rgb+flow. However, I didn't find the method to train two-stream in this repo.
Can you give me this training script？

Thanks!

**Comment by craston** [comment]
RGB and Flow networks are trained separately. Two stream (RGB + Flow ) are evaluated /tested by averaging their scores. For reference https://github.com/craston/MARS/blob/578e40fb64c141ce4f355d103d32b412d6bfd842/test_two_stream.py#L96
