### ISSUE TITLE
For Flow stream use test_single_stream.py

### ISSUE THREAD

**Issue by Maojianzeng** [craston/MARS#42]
Thank you for publishing the code !
I have a question about flow, in the extract_frames_flows.py, line 95 to line 96:

cv2.imwrite(os.path.join(outdir, 'TVL1jpg_x_%05d.jpg' % (i)), iflow[:, :, 0])
cv2.imwrite(os.path.join(outdir, 'TVL1jpg_y_%05d.jpg' % (i)), iflow[:, :, 1])

so the shape of the TVL1jpg_x.jpg and TVL1jpg_y.jpg are both (256,256), while in the test_single_stream.py, line 35 to line 36:

if opt.modality=='RGB': opt.input_channels = 3
elif opt.modality=='Flow': opt.input_channels = 2 

when I run the test_single_stream.py, it occured an error: Length of validation data = 0
I want know how it processes the two gray pictures to meet input_channels = 2.

**Comment by craston** [comment]
Please change the path in line https://github.com/craston/MARS/blob/578e40fb64c141ce4f355d103d32b412d6bfd842/utils1/extract_frames_flows.py#L79 . Most likely the optical flows haven't been extracted and therefore the length of validation data equals 0

**Comment by Maojianzeng** [comment]
> Please change the path in line
> 
> https://github.com/craston/MARS/blob/578e40fb64c141ce4f355d103d32b412d6bfd842/utils1/extract_frames_flows.py#L79
> 
> . Most likely the optical flows haven't been extracted and therefore the length of validation data equals 0

craston,
I have got the flow which has been saved like TVL1jpg_x_%05d.jpg and TVL1jpg_y_%05d.jpg at dataset/HMDB51_flow, and I have  successfully run the test_single_stream.py for RGB stream. The problem I meet is when I run the test_single_stream.py for Flow stream, use 

python test_single_stream.py --batch_size 1 --n_classes 51 --model resnext --model_depth 101  --log 1 --dataset HMDB51 --modality Flow --sample_duration 16 --split 1  --resume_path1 "trained_models/HMDB51/Flow_HMDB51_16f.pth"  --frame_dir "dataset/HMDB51_flow"  --annotation_path "dataset/HMDB51_labels"  --result_path "results/"

 it occured an error: Length of validation data = 0, can you explain this problem ?

**Comment by craston** [comment]
Can you please check if the dataset class is reading the files correctly? https://github.com/craston/MARS/blob/578e40fb64c141ce4f355d103d32b412d6bfd842/dataset/dataset.py#L192

**Comment by Maojianzeng** [comment]
> Please change the path in line
> 
> https://github.com/craston/MARS/blob/578e40fb64c141ce4f355d103d32b412d6bfd842/utils1/extract_frames_flows.py#L79
> 
> . Most likely the optical flows haven't been extracted and therefore the length of validation data equals 0

craston,
I have got the flow which has been saved like TVL1jpg_x_%05d.jpg and TVL1jpg_y_%05d.jpg at dataset/HMDB51_flow, and I have  successfully run the test_single_stream.py for RGB stream. The problem I meet is when I run the test_single_stream.py for Flow stream, use 

python test_single_stream.py --batch_size 1 --n_classes 51 --model resnext --model_depth 101  --log 1 --dataset HMDB51 --modality Flow --sample_duration 16 --split 1  --resume_path1 "trained_models/HMDB51/Flow_HMDB51_16f.pth"  --frame_dir "dataset/HMDB51_flow"  --annotation_path "dataset/HMDB51_labels"  --result_path "results/"

 it occured an error: Length of validation data = 0, can you explain this problem ?

> Can you please check if the dataset class is reading the files correctly?
> 
> https://github.com/craston/MARS/blob/578e40fb64c141ce4f355d103d32b412d6bfd842/dataset/dataset.py#L192

Thank you for your reply! I have found the solution. It is difficult for me to build OpenCV with GPU support, so I extract the optical flows in another way, but there is a detail in the utils1/extract_frames_flows.py:
[https://github.com/craston/MARS/blob/578e40fb64c141ce4f355d103d32b412d6bfd842/utils1/extract_frames_flows.py](url)
Line 93:  os.system('touch "%s"'%(os.path.join(outdir, 'done') ))

And in the dataset/dataset.py:
[https://github.com/craston/MARS/blob/578e40fb64c141ce4f355d103d32b412d6bfd842/dataset/dataset.py](url)
Line 195:  elif os.path.exists(frame_path) and "done" in os.listdir(frame_path):

The limiting condition "done" affects my work. I changed it as:
Line 195: elif os.path.exists(frame_path):
So the length of validation data not equals 0. It is really a great job, thank you again for you open the code！
