### ISSUE TITLE
percentage difference for previous SOTA paper

### ISSUE THREAD

**Issue by Fazlik995** [craston/MARS#5]
I have another question

In your paper RGB results for UCF-101 dataset is 95.2% for 64f-clip

In 'Can Spatiotemporal 3D CNNs Retrace the History of 2D CNNs and ImageNet' CVPR 2018 paper the result is 94.5%

However, approaches are the same in both cases(resnext-101).

Could you please explain, why your RGB result is higher than 94.5%.

I could not find any difference between your source code and 'Can Spatiotemporal 3D CNNs Retrace the History of 2D CNNs and ImageNet' paper's source code.

That is why i am wondering why two different results are obtained.

Maybe you added something which i have not mentioned in your code.

Thanks

**Comment by craston** [comment]
Hi,

One possible explanation for the higher accuracy of the RGB stream is in the way frames are extracted from the video. We specify higher quality frames while using ffmpeg using the -q option [(here)](https://github.com/craston/MARS/blob/ae2749dc37ec19821da69654e9197a52f0b45839/utils1/extract_frames.py#L48).

**Comment by Fazlik995** [comment]
Thank you!
