### ISSUE TITLE
HMDB51 training error!!!!

### ISSUE THREAD

**Issue by qiuqicao77** [craston/MARS#8]
Namespace(MARS=False, MARS_alpha=50.0, MARS_pretrain_path='', MARS_resume_path='', annotation_path='/media/cqq/Data/vicky/code/1action/MARS_dataset/dataset/HMDB51_labels/', batch_size=2, begin_epoch=1, checkpoint=1, dampening=0.9, dataset='HMDB51', frame_dir='/media/cqq/Data/vicky/code/1action/MARS_dataset/dataset/HMDB51_1/', freeze_BN=False, ft_begin_index=4, input_channels=3, learning_rate=0.1, log=1, lr_patience=10, manual_seed=1, modality='RGB_Flow', model='resnext', model_depth=101, momentum=0.9, n_classes=400, n_epochs=400, n_finetune_classes=51, n_workers=4, nesterov=False, only_RGB=False, optimizer='sgd', output_layers=["'avgpool'"], pretrain_path='/media/cqq/Data/vicky/code/1action/MARS/trained_models/MARS_Kinetics_64f.pth', random_seed=1, resnet_shortcut='B', resnext_cardinality=32, result_path='/media/cqq/Data/vicky/code/1action/MARS/results/', resume_path1='/media/cqq/Data/vicky/code/1action/MARS/trained_models/Flow_HMDB51_64f.pth', resume_path2='', resume_path3='', sample_duration=64, sample_size=112, split='1', training=True, weight_decay=0.001)
Preprocessing train data ...
Length of train data =  3570
Preprocessing validation data ...
Length of validation data =  1530
Preparing datatloaders ...
Length of train datatloader =  1785
Length of validation datatloader =  765
Loading MARS model...  resnext 101
loading pretrained model /media/cqq/Data/vicky/code/1action/MARS/trained_models/MARS_Kinetics_64f.pth
Layers to finetune :  ['layer4', 'fc']
Loading Flow model...  resnext 101
loading checkpoint /media/cqq/Data/vicky/code/1action/MARS/trained_models/Flow_HMDB51_64f.pth
Initializing the optimizer ...
lr = 0.001 	 momentum = 0.9 	 dampening = 0.9 	 weight_decay = 1e-05, 	 nesterov = False
LR patience =  10
run
Traceback (most recent call last):
  File "/media/cqq/Data/vicky/code/1action/MARS/masr_train.py", line 186, in <module>
    outputs_Flow = model_Flow(inputs_Flow)[1].detach()
IndexError: list index out of range

The length of the model_Flow is 1, so the list index out of range how can i fix this?
Thansk

**Comment by tadbeer** [comment]
> Namespace(MARS=False, MARS_alpha=50.0, MARS_pretrain_path='', MARS_resume_path='', annotation_path='/media/cqq/Data/vicky/code/1action/MARS_dataset/dataset/HMDB51_labels/', batch_size=2, begin_epoch=1, checkpoint=1, dampening=0.9, dataset='HMDB51', frame_dir='/media/cqq/Data/vicky/code/1action/MARS_dataset/dataset/HMDB51_1/', freeze_BN=False, ft_begin_index=4, input_channels=3, learning_rate=0.1, log=1, lr_patience=10, manual_seed=1, modality='RGB_Flow', model='resnext', model_depth=101, momentum=0.9, n_classes=400, n_epochs=400, n_finetune_classes=51, n_workers=4, nesterov=False, only_RGB=False, optimizer='sgd', output_layers=["'avgpool'"], pretrain_path='/media/cqq/Data/vicky/code/1action/MARS/trained_models/MARS_Kinetics_64f.pth', random_seed=1, resnet_shortcut='B', resnext_cardinality=32, result_path='/media/cqq/Data/vicky/code/1action/MARS/results/', resume_path1='/media/cqq/Data/vicky/code/1action/MARS/trained_models/Flow_HMDB51_64f.pth', resume_path2='', resume_path3='', sample_duration=64, sample_size=112, split='1', training=True, weight_decay=0.001)
> Preprocessing train data ...
> Length of train data = 3570
> Preprocessing validation data ...
> Length of validation data = 1530
> Preparing datatloaders ...
> Length of train datatloader = 1785
> Length of validation datatloader = 765
> Loading MARS model... resnext 101
> loading pretrained model /media/cqq/Data/vicky/code/1action/MARS/trained_models/MARS_Kinetics_64f.pth
> Layers to finetune : ['layer4', 'fc']
> Loading Flow model... resnext 101
> loading checkpoint /media/cqq/Data/vicky/code/1action/MARS/trained_models/Flow_HMDB51_64f.pth
> Initializing the optimizer ...
> lr = 0.001 momentum = 0.9 dampening = 0.9 weight_decay = 1e-05, nesterov = False
> LR patience = 10
> run
> Traceback (most recent call last):
> File "/media/cqq/Data/vicky/code/1action/MARS/masr_train.py", line 186, in
> outputs_Flow = model_Flow(inputs_Flow)[1].detach()
> IndexError: list index out of range
> 
> The length of the model_Flow is 1, so the list index out of range how can i fix this?
> Thansk

Hi Qiuqicao77 , I am also encountering the same problem. Please help with this. Thanks in advance.

**Comment by tianhuat** [comment]
Same problem here...Any idea how to resolve this? Even a short guide will be very helpful...

**Comment by tianhuat** [comment]
Got it resolved, in my case, change the parameter 
`--output_layers 'avgpool' `
to 
`--output_layers ”avgpool“ `
would work. 

This error only happens when I use Pycharm, it looks like Pycharm treats ' as a string,  and therefore last layers becomes literally 'avgpool', and this makes line 190 in resnext.py
`if i == 'avgpool':` not being able to detect it.
