### ISSUE TITLE
Question about training 64f parameter?

### ISSUE THREAD

**Issue by qiuqicao77** [craston/MARS#9]
Hello,  i got a question about whether the parameter of training 64f the MARS model in HMDB dataset is the same as 16f ?

**Comment by craston** [comment]
Yes, they are the same as 16f

**Comment by qiuqicao77** [comment]
May i ask one more question? When the training the 64f Flow HMDB51 with the
pretrained model 'Kinetics', however the accuracy of the 400 epoch model
cannot reach the result as yours. Can you give me some advice on this?

craston <notifications@github.com> 于2019年9月25日周三 下午2:41写道：
